#
# Module manifest for module 'JeaConfig'
#
# Generated by: Chris
#
# Generated on: 08/06/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'JeaConfig.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = 'cc05b7a9-4d36-4f02-a2ba-5b319dd28699'

# Author of this module
Author = 'Chris Gardner'

# Company or vendor of this module
CompanyName = 'Chris Gardner'

# Copyright statement for this module
Copyright = '(c) 2019 Chris. All rights reserved.'

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @('JeaDsc')

# DSC resources to export from this module
DscResourcesToExport = @('JeaConfig')

}

